In [190]:
import numpy as np

In [192]:
#1
a = np.zeros((3,4))

In [194]:
#2
z=0
for i in range(len(a)) :
    for j in range(len(a[i])):
        z+=1
        a[i,j] = z
print(a)

In [196]:
#3
print(a[1,2])

7.0


In [198]:
#4
print(a[1:2, :])

[[5. 6. 7. 8.]]


In [204]:
#5
print(a[:,1:3])

[[ 2.  3.]
 [ 6.  7.]
 [10. 11.]]


In [200]:
#6
print(a[a<=6])

[1. 2. 3. 4. 5. 6.]


In [238]:
#7
np.random.seed(7)
b=np.random.random((3,4))
print(b)

[[0.07630829 0.77991879 0.43840923 0.72346518]
 [0.97798951 0.53849587 0.50112046 0.07205113]
 [0.26843898 0.4998825  0.67923    0.80373904]]


In [240]:
#8
c=a*b
print(c)

[[0.07630829 1.55983758 1.31522769 2.89386071]
 [4.88994756 3.23097522 3.50784325 0.57640907]
 [2.41595082 4.99882501 7.47152996 9.64486843]]


In [252]:
#9
d=b.T
print(d)

[[0.07630829 0.97798951 0.26843898]
 [0.77991879 0.53849587 0.4998825 ]
 [0.43840923 0.50112046 0.67923   ]
 [0.72346518 0.07205113 0.80373904]]


In [254]:
#10
print(a.shape)
print(d.shape)

(3, 4)
(4, 3)


In [256]:
#11
e=np.dot(a, d)
print(e)

[[ 5.84523428  3.84654718  6.52085011]
 [13.91764024 12.20517509 15.52601217]
 [21.99004621 20.56380301 24.53117422]]


In [258]:
#12
print(np.sum(e, axis=0))

[41.75292073 36.61552528 46.5780365 ]
